### ISSUE TITLE
KeyError: 'mixtral'

### ISSUE THREAD

**Issue by BBaekdabang** [mobiusml/hqq#1]
The error message is as follows

`KeyError: 'mixtral'`

**Comment by appoose** [comment]
Can you update to the latest version of transformer library? This should ideally fix the mixtral key missing problem. 

pip install -U transformers

**Comment by BBaekdabang** [comment]
Thanks !
I solve that problem, but one more error....
`AttributeError: 'NoneType' object has no attribute 'hqq_quantized'`

**Comment by mobicham** [comment]
Can you provide a code snippet to reproduce this?

**Comment by BBaekdabang** [comment]
```
model_id = '/home/Mixtral-8x7B-Instruct-v0.1-hf-4bit_g64-HQQ'

#Load the model
from hqq.engine.hf import HQQModelForCausalLM, AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained(model_id)
model     = HQQModelForCausalLM.from_quantized(model_id)

#Optional
from hqq.core.quantize import *
HQQLinear.set_backend(HQQBackend.PYTORCH_COMPILE) 

#Text Generation
prompt = "<s> [INST] How do I build a car? [/INST] "

inputs = tokenizer(prompt, return_tensors="pt", add_special_tokens=False)
outputs = model.generate(**(inputs.to('cuda')), max_new_tokens=1000)
print(tokenizer.decode(outputs[0], skip_special_tokens=True))
```

**Comment by mobicham** [comment]
I just tried in a fresh instance and it works fine. My guess is that you are using a slightly older version of HQQ. 
Can you try the following:
```
pip uninstall hqq
git clone https://github.com/mobiusml/hqq.git;
cd hqq && pip install . && cd ..;
pip install transformers --upgrade
huggingface-cli login --token <your_huggingface_token>

<your code>
```

**Comment by BBaekdabang** [comment]
![image](https://github.com/mobiusml/hqq/assets/113493692/683884f6-2686-45e5-8038-9e92d16dbb04)
![image](https://github.com/mobiusml/hqq/assets/113493692/febdadd9-b97d-4c1e-b212-ae679c739d83)
Do u know why this error occured?

**Comment by mobicham** [comment]
Are you using Google Colab? Try this: https://github.com/pytorch/pytorch/issues/107960#issuecomment-1783432552

**Comment by michaelfeil** [comment]
@BBaekdabang Try to `import torch` first, before improting `import hhq`. Also make sure that torch recognizes your GPU, ie `torch.cuda.is_available() `
