### ISSUE TITLE
Question about Quantization

### ISSUE THREAD

**Issue by NEWbie0709** [mobiusml/hqq#113]
Hey, it's me again! 😆 I've done testing on the HQQ pre-trained model inside the Linux system, and it is working well with the custom transformer code you gave me. Now, I want to test the quantization for this model, and this is my code. Can you give any suggestions for it?

https://huggingface.co/akjindal53244/Llama-3.1-Storm-8B

import torch

model_id  = "akjindal53244/Llama-3.1-Storm-8B" 

compute_dtype = torch.bfloat16
device     = "cuda"
cache_path = "."

from transformers import AutoModelForCausalLM, AutoTokenizer
from hqq.models.hf.base import AutoHQQHFModel
#from hqq.models.hf.llama import LlamaHQQ as AutoHQQHFModel #OR for llama models
from hqq.core.quantize import *

model     = AutoModelForCausalLM.from_pretrained(model_id, cache_dir=cache_path, torch_dtype=compute_dtype)
tokenizer = AutoTokenizer.from_pretrained(model_id, cache_dir=cache_path) 

quant_config = BaseQuantizeConfig(nbits=4, group_size=64, quant_scale=False, quant_zero=False, axis=1) 
AutoHQQHFModel.quantize_model(model, quant_config=quant_config, compute_dtype=compute_dtype, device=device)

dir_s = 'output/Llama-3.1-Storm-8B_HQQ_4bit'
AutoHQQHFModel.save_quantized(model, dir_s)

**Comment by NEWbie0709** [comment]
successfully ran the quantization code above, but when I tried to test it, it showed some errors. This is the code
`import torch
from transformers import AutoTokenizer
from hqq.models.hf.base import AutoHQQHFModel
from hqq.utils.patching import *
from hqq.core.quantize import *
from hqq.utils.generation_hf import HFGenerator

#Load the model
###################################################
#model_id = 'mobiuslabsgmbh/Llama-3.1-8b-instruct_4bitgs64_hqq' #no calib version
model_id = "akjindal53244/Llama-3.1-Storm-8B"  #calibrated version
compute_dtype = torch.bfloat16 #bfloat16 for torchao, float16 for bitblas
cache_dir = '.'
device = 'cuda:0'
model = AutoHQQHFModel.from_quantized("output/Llama-3.1-Storm-8B_HQQ_4bit")
tokenizer = AutoTokenizer.from_pretrained(model_id, cache_dir=cache_dir)

quant_config = BaseQuantizeConfig(nbits=4, group_size=64, quant_scale=False, quant_zero=False, axis=1)
patch_linearlayers(model, patch_add_quant_config, quant_config)

#Use optimized inference kernels
###################################################
HQQLinear.set_backend(HQQBackend.PYTORCH)
#prepare_for_inference(model) #default backend
prepare_for_inference(model,backend="torchao_int4")
#prepare_for_inference(model, backend="bitblas") #takes a while to init...

#Generate
###################################################
#For longer context, make sure to allocate enough cache via the cache_size= parameter
gen = HFGenerator(model, tokenizer, max_new_tokens=1000, do_sample=True, compile="partial").warmup() #Warm-up takes a while

import time
t1 = time.time()
gen.generate("Write an essay about large language models", print_tokens=True)
t2 = time.time()
print('Took', t2-t1, 'secs')`

and this is the error shown

> Traceback (most recent call last):
>   File "/mnt/c/users/i9-4090/documents/tianyi/storm_testing.py", line 25, in <module>
>     prepare_for_inference(model,backend="torchao_int4")
>   File "/home/user/miniconda3/envs/hqq/lib/python3.9/site-packages/hqq/utils/patching.py", line 116, in prepare_for_inference
>     patch_linearlayers(model, patch_hqq_to_aoint4, verbose=verbose)
>   File "/home/user/miniconda3/envs/hqq/lib/python3.9/site-packages/hqq/utils/patching.py", line 25, in patch_linearlayers
>     model.base_class.patch_linearlayers(
>   File "/home/user/miniconda3/envs/hqq/lib/python3.9/site-packages/hqq/models/base.py", line 154, in patch_linearlayers
>     patch_fct(tmp_mapping[name], patch_param),
>   File "/home/user/miniconda3/envs/hqq/lib/python3.9/site-packages/hqq/backends/torchao.py", line 314, in patch_hqq_to_aoint4
>     hqq_aoint4_layer = HQQLinearTorchWeightOnlynt4(
>   File "/home/user/miniconda3/envs/hqq/lib/python3.9/site-packages/hqq/backends/torchao.py", line 73, in __init__
>     assert (
> AssertionError: Only bfloat16 compute_dtype is supported.

**Comment by NEWbie0709** [comment]
but i manage to solve it when i run the testing code directly after quantizing the model this is the code i using
```
import torch
from transformers import AutoTokenizer
from hqq.models.hf.base import AutoHQQHFModel
from hqq.utils.patching import *
from hqq.core.quantize import *
from hqq.utils.generation_hf import HFGenerator

model_id  = "akjindal53244/Llama-3.1-Storm-8B" 

compute_dtype = torch.bfloat16
device     = "cuda"
cache_path = "."

from transformers import AutoModelForCausalLM, AutoTokenizer
from hqq.models.hf.base import AutoHQQHFModel
#from hqq.models.hf.llama import LlamaHQQ as AutoHQQHFModel #OR for llama models
from hqq.core.quantize import *

model     = AutoModelForCausalLM.from_pretrained(model_id, cache_dir=cache_path, torch_dtype=compute_dtype)
tokenizer = AutoTokenizer.from_pretrained(model_id, cache_dir=cache_path) 

quant_config = BaseQuantizeConfig(nbits=4, group_size=64, quant_scale=False, quant_zero=False, axis=1) 
AutoHQQHFModel.quantize_model(model, quant_config=quant_config, compute_dtype=compute_dtype, device=device)

prepare_for_inference(model,backend="torchao_int4")
#prepare_for_inference(model, backend="bitblas") #takes a while to init...

#Generate
###################################################
#For longer context, make sure to allocate enough cache via the cache_size= parameter
gen = HFGenerator(model, tokenizer, max_new_tokens=1000, do_sample=True, compile="partial").warmup() #Warm-up takes a while

import time
t1 = time.time()
gen.generate("Write an essay about large language models", print_tokens=True)
t2 = time.time()
print('Took', t2-t1, 'secs')
```

**Comment by mobicham** [comment]
When you are loading a quantized model, you need to specify the `compute_dtype`  (default `torch.float16`) and the device if necessary:

```Python
model = AutoHQQHFModel.from_quantized("output/Llama-3.1-Storm-8B_HQQ_4bit", compute_dtype=torch.bfloat16, device='cuda:0')
```
`torch.bfloat16` is because you are using the `torchao_int4` backend which only supports `bfloat16`
See the examples on the HF repo: https://huggingface.co/mobiuslabsgmbh/Llama-3.1-8b-instruct_4bitgs64_hqq_calib

**Comment by NEWbie0709** [comment]
Thanks! It's working 😄

**Comment by NEWbie0709** [comment]
Hi, I tried the same ways to quantize and load the HQQ quantized model, but right now I am quantizing the Qwen/Qwen2-VL-2B-Instruct model.  [https://huggingface.co/Qwen/Qwen2-VL-2B-Instruct]
![image](https://github.com/user-attachments/assets/cf634d03-6448-4563-bd09-56a26148c143)
When I load the quantized model, it shows the error below.

> (hqq) user@AMARIS-i9-4090:/mnt/c/users/i9-4090/documents/tianyi$ python storm_testing.py
> Warning: failed to import the BitBlas backend. Check if BitBlas is correctly installed if you want to use the bitblas backend (https://github.com/microsoft/BitBLAS).
> /home/user/miniconda3/envs/hqq/lib/python3.9/site-packages/hqq/models/base.py:251: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
>   return torch.load(cls.get_weight_file(save_dir), map_location=map_location)
>   0%|                                                                                           | 0/114 [00:00<?, ?it/s]
> Traceback (most recent call last):
>   File "/mnt/c/users/i9-4090/documents/tianyi/storm_testing.py", line 16, in <module>
>     model = AutoHQQHFModel.from_quantized("output/Qwen2-VL-2B-Instruct", compute_dtype=torch.bfloat16, device='cuda')
>   File "/home/user/miniconda3/envs/hqq/lib/python3.9/site-packages/hqq/models/base.py", line 517, in from_quantized
>     cls.patch_model(
>   File "/home/user/miniconda3/envs/hqq/lib/python3.9/site-packages/hqq/models/base.py", line 215, in patch_model
>     cls.patch_nonlinearlayers(model, patch_nonlinear_fct, verbose=verbose)
>   File "/home/user/miniconda3/envs/hqq/lib/python3.9/site-packages/hqq/models/base.py", line 125, in patch_nonlinearlayers
>     patch_fct(tmp_mapping[name]),
>   File "/home/user/miniconda3/envs/hqq/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
>     return func(*args, **kwargs)
>   File "/home/user/miniconda3/envs/hqq/lib/python3.9/site-packages/hqq/models/base.py", line 490, in _load_module
>     return module.to(device=device, dtype=compute_dtype, non_blocking=True)
>   File "/home/user/miniconda3/envs/hqq/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1340, in to
>     return self._apply(convert)
>   File "/home/user/miniconda3/envs/hqq/lib/python3.9/site-packages/torch/nn/modules/module.py", line 927, in _apply
>     param_applied = fn(param)
>   File "/home/user/miniconda3/envs/hqq/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1333, in convert
>     raise NotImplementedError(
> NotImplementedError: Cannot copy out of meta tensor; no data! Please use torch.nn.Module.to_empty() instead of torch.nn.Module.to() when moving module from meta to a different device.


Other than that, do you have any ways to load the quantized PT model other than using the generator from HQQ?

**Comment by NEWbie0709** [comment]
And if i run directly without saving the quantized model? it will show this error

> Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.47it/s]
> 100%|█████████████████████████████████████████████████████████████████████████████████| 214/214 [00:06<00:00, 31.13it/s]
> 100%|█████████████████████████████████████████████████████████████████████████████████| 327/327 [00:30<00:00, 10.56it/s]
> Traceback (most recent call last):
>   File "/mnt/c/users/i9-4090/documents/tianyi/quantize.py", line 31, in <module>
>     gen = HFGenerator(model, tokenizer, max_new_tokens=1000, do_sample=True, compile="partial").warmup() #Warm-up takes a while
>   File "/home/user/miniconda3/envs/hqq/lib/python3.9/site-packages/hqq/utils/generation_hf.py", line 100, in warmup
>     self.generate(prompt, print_tokens=False);
>   File "/home/user/miniconda3/envs/hqq/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
>     return func(*args, **kwargs)
>   File "/home/user/miniconda3/envs/hqq/lib/python3.9/site-packages/hqq/utils/generation_hf.py", line 253, in generate
>     return self.next_token_iterator(self.prefill(), self.max_new_tokens, verbose, print_tokens)
>   File "/home/user/miniconda3/envs/hqq/lib/python3.9/site-packages/hqq/utils/generation_hf.py", line 183, in prefill
>     out = self.model(
>   File "/home/user/miniconda3/envs/hqq/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "/home/user/miniconda3/envs/hqq/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
>     return forward_call(*args, **kwargs)
> TypeError: forward() got an unexpected keyword argument 'cache_position'


this is the code i using
```
import torch

model_id = "Qwen/Qwen2-VL-2B-Instruct"
compute_dtype = torch.bfloat16
device = "cuda"
cache_path = "."

from transformers import AutoModelForCausalLM, AutoTokenizer,Qwen2VLForConditionalGeneration
from hqq.models.hf.base import AutoHQQHFModel
#from hqq.models.hf.llama import LlamaHQQ as AutoHQQHFModel #OR for llama models
from hqq.core.quantize import *
from hqq.utils.patching import *
from hqq.utils.generation_hf import HFGenerator

model = Qwen2VLForConditionalGeneration.from_pretrained(model_id, cache_dir=cache_path, torch_dtype=compute_dtype)
tokenizer = AutoTokenizer.from_pretrained(model_id, cache_dir=cache_path)

quant_config = BaseQuantizeConfig(nbits=4, group_size=None, quant_scale=False, quant_zero=False, axis=1)
AutoHQQHFModel.quantize_model(model, quant_config=quant_config, compute_dtype=compute_dtype, device=device)

# #Use optimized inference kernels
# ###################################################
HQQLinear.set_backend(HQQBackend.PYTORCH)
# #prepare_for_inference(model) #default backend
prepare_for_inference(model,backend="torchao_int4")
# #prepare_for_inference(model, backend="bitblas") #takes a while to init...

# #Generate
# ###################################################
# #For longer context, make sure to allocate enough cache via the cache_size= parameter
gen = HFGenerator(model, tokenizer, max_new_tokens=1000, do_sample=True, compile="partial").warmup() #Warm-up takes a while
```
