### ISSUE TITLE
Hqq vs gguf

### ISSUE THREAD

**Issue by blap** [mobiusml/hqq#118]
Is there an easy way to convert gguf to hqq and vice-versa? Any comparisons?
https://github.com/leafspark/AutoGGUF

**Comment by mobicham** [comment]
Hi! What of quantization is GGUF using? If it's asymmetric quantization (with both scales/zeros) it could be converted

**Comment by blap** [comment]
> Hi! What of quantization is GGUF using? If it's asymmetric quantization (with both scales/zeros) it could be converted

Sorry. I don't know the specs, but here you can see details about it and how to convert hf to gguf from llama.cpp: https://github.com/ggerganov/llama.cpp/tree/master/gguf-py

**Comment by mobicham** [comment]
Thanks for sharing,  looks like the logic is quite different, so I don't think both quantized outputs are compatible unfortunately.
