### ISSUE TITLE
optimize_weights_proximal_legacy: Zero updated before potential break. Causes zero of next iteration to be returned as best value.

### ISSUE THREAD

**Issue by RobertBiehl** [mobiusml/hqq#13]
I think the optimize_weights_proximal_legacy method has a bug. 

Zero is getting updated before potential break. This causes zero of next iteration to be returned as best value.

https://github.com/mobiusml/hqq/blob/96ce17dc132757b1fde8d4d6f78748908277c80c/hqq/core/optimize.py#L165

(On the phone so can’t test/create PR right now)

**Comment by mobicham** [comment]
Hi @RobertBiehl, 
Thanks for your message! Yes I know, but it's really a big issue, this only results in an additional step. It has already been fixed in optimize_weights_proximal_v2
