### ISSUE TITLE
 AttributeError: module 'torch' has no attribute 'compile'

### ISSUE THREAD

**Issue by PtrMan** [mobiusml/hqq#15]
I did install it on a fresh machine with

    !pip install -U torch
    !pip install -U transformers
    !pip install -U hqq

<br />

    ---------------------------------------------------------------------------
    AttributeError                            Traceback (most recent call last)
    Input In [1], in <cell line: 6>()
          4 model_id = 'mobiuslabsgmbh/Mixtral-8x7B-Instruct-v0.1-hf-attn-4bit-moe-2bit-metaoffload-HQQ'
          5 #Load the model
    ----> 6 from hqq.engine.hf import HQQModelForCausalLM, AutoTokenizer
          7 tokenizer = AutoTokenizer.from_pretrained(model_id)
          8 model     = HQQModelForCausalLM.from_quantized(model_id)
    
    File /usr/local/lib/python3.9/dist-packages/hqq/engine/hf.py:6, in <module>
          2 from typing import Dict
          4 _HQQ_REGISTRY = {}
    ----> 6 from ..models.hf.llama import LlamaHQQ
          7 _HQQ_REGISTRY['LlamaForCausalLM'] = LlamaHQQ
          9 from hqq.models.hf.mixtral import MixtralHQQ
    
    File /usr/local/lib/python3.9/dist-packages/hqq/models/hf/llama.py:1, in <module>
    ----> 1 from ..base import *
          2 from .base  import *
          4 #Patch LLama functions
    
    File /usr/local/lib/python3.9/dist-packages/hqq/models/base.py:9, in <module>
          6 from abc import abstractmethod
          8 from huggingface_hub import snapshot_download
    ----> 9 from ..core.quantize import HQQLinear
         11 #Cleanup GPU vram
         12 def cleanup():
    
    File /usr/local/lib/python3.9/dist-packages/hqq/core/quantize.py:246, in <module>
        243 		return grad_input, grad_weight, grad_bias
        245 #Main linear layer 
    --> 246 class HQQLinear(torch.nn.Module):
        247 	backend = HQQBackend.PYTORCH #Default
        249 	def __init__(self, linear_layer, quant_config, del_orig=True, compute_dtype=torch.float16, device_n=0):
    
    File /usr/local/lib/python3.9/dist-packages/hqq/core/quantize.py:389, in HQQLinear()
        386 	weight = self.dequantize() 
        387 	return torch.matmul(x, weight.t() if (transpose) else weight)
    --> 389 @torch.compile()
        390 def matmul_compile(self, *args, **kwargs):
        391 	return self.matmul(*args, **kwargs)
        393 def forward_pytorch_backprop(self, x):
    
    AttributeError: module 'torch' has no attribute 'compile'

this probably occurs because it needs the wrong pytorch version (1.X) which doesnt feature compile .

A hack to prevent this is to install pytorch 2.X after installing HQQ

**Comment by mobicham** [comment]
Thank you for your comment!
The documentation explicitly says that you need to install Pytorch 2 (First, make sure you have a Pytorch 2 version that matches your CUDA version: https://pytorch.org/) 
HQQ doesn't install Pytorch because it's integrated into other projects and automatically installing Pytorch was creating many issues, so we encourage the user to install their own version of Pytorch 2

**Comment by MarkBenjamin** [comment]
You may need the pytorch nightly build too
