### ISSUE TITLE
Support for Mixtral with vLLM

### ISSUE THREAD

**Issue by HaritzPuerto** [mobiusml/hqq#28]
Hi, I'm trying your quantized Mixtral and it's amazing!! Huge congrats! This is super useful!

I've been able to try it without vLLM but it seems it's not possible to load with vLLM yet. I guess adding this support is already in your backlog; I just wanted to point out that I'm looking forward to it, and thank you for this amazing work!

Best,
Haritz

**Comment by mobicham** [comment]
Very happy to hear that @HaritzPuerto !
I think we will need to scratch everything we did for VLLM in this repo and either do a PR to directly integrate HQQ into the main VLLM repo or have a separate VLLM forked repo.
