### ISSUE TITLE
`.to` is not supported for HQQ-quantized models

### ISSUE THREAD

**Issue by Abdullah-kwl** [mobiusml/hqq#39]
I want to quantize "senseable/WestLake-7B-v2" as I do using transformer and BnB, 

As you mention in https://github.com/mobiusml/hqq/issues/34#issuecomment-2029731761
I downloaded the transformer library from your repo https://github.com/mobiusml/transformers.git from **Branch "stable"**.
then I downloaded the hqq using : pip install git+https://github.com/mobiusml/hqq.git.

then I use [hqq_transformers_llama_example.py](https://gist.github.com/mobicham/cb07c1eff443ad0918c49ab7bb03e269) to quantize my model but facing the issue "`.to` is not supported for HQQ-quantized models", is it due to I use cuda?

![Screenshot 2024-04-02 173733](https://github.com/mobiusml/hqq/assets/101694671/db38e6b3-673b-4b76-9b9c-5d6058b6f6c4)
![Screenshot 2024-04-02 173648](https://github.com/mobiusml/hqq/assets/101694671/505ca2fb-7eea-4e7a-86f3-0bb36a4cfd63)

**Comment by mobicham** [comment]
Hi, the branch and the example: https://gist.github.com/mobicham/cb07c1eff443ad0918c49ab7bb03e269 are working fine, I just tried it now. Make sure:
- You have a clean installation of ```transformers``` from https://github.com/mobiusml/transformers/tree/stable (not main)
- Make sure the GPU is selected in the Colab session

**Comment by Abdullah-kwl** [comment]
I used the same transformer from the **stable** branch https://github.com/mobiusml/transformers/tree/stable, but facing the same issue ,
I am also using GPU ,

Please Review my code if there is any mistake:

#cloned repo of transformer from **stable branch**  https://github.com/mobiusml/transformers/tree/stable
#download hqq from **master branch** repo https://github.com/mobiusml/hqq

!pip install git+https://github.com/Abdullah-kwl/Transformers-HQQ-Integration.git
!pip install git+https://github.com/mobiusml/hqq.git

import torch, transformers
from hqq.core.quantize import *

model_id      = "senseable/WestLake-7B-v2"

**#Basic**
quant_config  = BaseQuantizeConfig(nbits=4, group_size=64)
cache_path    = ''
compute_dtype = torch.float16
device        = 'cuda:0'

**#pass BaseQuantizeConfig to AutoModelForCausalLM**

model     = transformers.AutoModelForCausalLM.from_pretrained(model_id,
                                                              cache_dir=cache_path, 
                                                              torch_dtype=compute_dtype,
                                                              device_map=device,
                                                              quantization_config=transformers.HQQConfig(quant_config))

tokenizer = transformers.AutoTokenizer.from_pretrained(model_id)


After this cell run it do every thing but in last it show the error **ValueError: `.to` is not supported for HQQ-quantized models.**
[.to is not supported for HQQ-quantized models](https://github.com/mobiusml/hqq/issues/39#top)
#39

![Screenshot 2024-04-06 130608](https://github.com/mobiusml/hqq/assets/101694671/fb6271c5-251c-4aa8-97b8-18c1ea7db614)

please look at https://github.com/mobiusml/transformers/blob/stable/src/transformers/modeling_utils.py
**this is from transformer stabel branch**

![Screenshot 2024-04-06 130321](https://github.com/mobiusml/hqq/assets/101694671/71a1b7a1-8c6a-4c17-839e-7cc5816ab7fa)

**Comment by mobicham** [comment]
Strange, I tried the same branch and it worked, with Llama2-7B. Can you with Llama2-7B?

**Comment by mobicham** [comment]
Try using HQQ with transformers: https://github.com/huggingface/transformers/pull/29637
