### ISSUE TITLE
transfer learning?

### ISSUE THREAD

**Issue by NickyDark1** [mobiusml/hqq#40]
Thank you for this great project.
I wanted to ask you, when I reduce it to 4 bits, for example, and then train it with the new data, I'm not sure if it's possible to merge the 4-bit model with the complete model to perform knowledge transfer?

**Comment by mobicham** [comment]
Thank you!
I am not sure about that. You mean have the behavior of both the full-precision and 4-bit models ?

**Comment by mobicham** [comment]
Closing since there was no follow-up.
