### ISSUE TITLE
An error occurred when I was training a 1bit model using lora........(element 0 of tensors does not require grad and does not have a grad_fn)

### ISSUE THREAD

**Issue by Minami-su** [mobiusml/hqq#41]
```

	model = AutoHQQHFModel.from_quantized(base_model).cuda()
	# Add Peft
	######################################################################################
	train_dtype = torch.float32
	base_lora_params = {'lora_type': 'default', 'r': 16, 'lora_alpha': 32, 'dropout': 0.05, 'train_dtype': train_dtype}
	lora_params = {'self_attn.q_proj': base_lora_params,
				   'self_attn.k_proj': base_lora_params,
				   'self_attn.v_proj': base_lora_params,
				   'self_attn.o_proj': base_lora_params,
				   'mlp.gate_proj': base_lora_params,
				   'mlp.up_proj': base_lora_params,
				   'mlp.down_proj': base_lora_params, }

	# Apply LoRA
	PeftUtils.add_lora(model, lora_params)

	data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)
	trainer = transformers.Trainer(
		model=model,
		train_dataset=train_data,
		eval_dataset=val_data,
		args=transformers.TrainingArguments(
			per_device_train_batch_size=micro_batch_size,
			gradient_accumulation_steps=gradient_accumulation_steps,
			warmup_steps=0,
			num_train_epochs=num_epochs,
			learning_rate=learning_rate,
			fp16=True,
			logging_steps=50,
			optim="adamw_torch",
			gradient_checkpointing=True,
			gradient_checkpointing_kwargs={'use_reentrant': True},
			evaluation_strategy="steps" if val_set_size > 0 else "no",
			save_strategy="steps",
			eval_steps=100 if val_set_size > 0 else None,
			save_steps=200,
			output_dir=output_dir,
			save_total_limit=2,
			report_to="wandb" if use_wandb else None,
			run_name=wandb_run_name if use_wandb else None,
			remove_unused_columns=False,
			max_grad_norm=1.0,
		),
		data_collator=data_collator
	)



	signal.signal(signal.SIGINT, save_model)
	model.train()
	trainer.train()
	model.save_pretrained(output_dir)

	print(
		"\n If there's a warning about missing keys above, please disregard :)"
	)


if __name__ == "__main__":
	fire.Fire(train)

```

Map: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 1000/1000 [00:00<00:00, 4859.96 examples/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 258/258 [00:00<00:00, 286.99it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 449/449 [00:16<00:00, 27.09it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 22550.02it/s]
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
/root/miniconda3/envs/train/lib/python3.10/site-packages/accelerate/accelerator.py:432: FutureWarning: Passing the following arguments to `Accelerator` is deprecated and will be removed in version 1.0 of Accelerate: dict_keys(['dispatch_batches', 'split_batches', 'even_batches', 'use_seedable_sampler']). Please pass an `accelerate.DataLoaderConfiguration` instead: 
dataloader_config = DataLoaderConfiguration(dispatch_batches=None, split_batches=False, even_batches=True, use_seedable_sampler=True)
  warnings.warn(
Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
  0%|                                                                                                                              | 0/1 [00:00<?, ?it/s]`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`.
/root/miniconda3/envs/train/lib/python3.10/site-packages/torch/utils/checkpoint.py:90: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
/root/miniconda3/envs/train/lib/python3.10/site-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '
Traceback (most recent call last):
  File "/root/autodl-tmp/ft_4bit_freedom-hqq-lora2.py", line 271, in <module>
    fire.Fire(train)
  File "/root/miniconda3/envs/train/lib/python3.10/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/root/miniconda3/envs/train/lib/python3.10/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/root/miniconda3/envs/train/lib/python3.10/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/root/autodl-tmp/ft_4bit_freedom-hqq-lora2.py", line 262, in train
    trainer.train()
  File "/root/miniconda3/envs/train/lib/python3.10/site-packages/transformers/trainer.py", line 1780, in train
    return inner_training_loop(
  File "/root/miniconda3/envs/train/lib/python3.10/site-packages/transformers/trainer.py", line 2118, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/root/miniconda3/envs/train/lib/python3.10/site-packages/transformers/trainer.py", line 3045, in training_step
    self.accelerator.backward(loss)
  File "/root/miniconda3/envs/train/lib/python3.10/site-packages/accelerate/accelerator.py", line 1999, in backward
    self.scaler.scale(loss).backward(**kwargs)
  File "/root/miniconda3/envs/train/lib/python3.10/site-packages/torch/_tensor.py", line 522, in backward
    torch.autograd.backward(
  File "/root/miniconda3/envs/train/lib/python3.10/site-packages/torch/autograd/__init__.py", line 266, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
  0%|                                                                                                                              | 0/1 [00:03<?, ?it/s]

**Comment by Sneakr** [comment]
I think this can help:
def enable_gradients(model):
    for param in model.parameters():
        param.requires_grad = True

**Comment by Minami-su** [comment]
> I think this can help: def enable_gradients(model): for param in model.parameters(): param.requires_grad = True

Traceback (most recent call last):
  File "/root/autodl-tmp/ft_4bit_freedom-hqq-lora2.py", line 276, in <module>
    fire.Fire(train)
  File "/root/miniconda3/envs/train/lib/python3.10/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/root/miniconda3/envs/train/lib/python3.10/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/root/miniconda3/envs/train/lib/python3.10/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/root/autodl-tmp/ft_4bit_freedom-hqq-lora2.py", line 229, in train
    model=enable_gradients(model)
  File "/root/autodl-tmp/ft_4bit_freedom-hqq-lora2.py", line 205, in enable_gradients
    param.requires_grad = True
RuntimeError: only Tensors of floating point and complex dtype can require gradients

**Comment by Minami-su** [comment]
> I think this can help: def enable_gradients(model): for param in model.parameters(): param.requires_grad = True

I think lora may not be used in this code PeftUtils.add_lora(model, lora_params)

**Comment by Minami-su** [comment]
@mobicham

**Comment by mobicham** [comment]
Can you follow this example: https://github.com/mobiusml/hqq/blob/master/examples/lora/train_hqq_lora_example.py

**Comment by Minami-su** [comment]
> Can you follow this example: https://github.com/mobiusml/hqq/blob/master/examples/lora/train_hqq_lora_example.py You may need to wrap your model:
> 
> ```python
> class WrappedModel(torch.nn.Module):
> 	def __init__(self, model):
> 		super().__init__()
> 		self.model = model
> 
> 	def forward(self, *args, **kwargs):
> 		return self.model.forward(*args, **kwargs)
> 
> 	def train(self):
> 		self.model.train()
> 
> 	def eval(self):
> 		self.model.eval()
> 
> 	def parameters(self):
> 		return self.model.parameters()
> 
> trainer = SFTTrainer(
>     model=WrappedModel(model),
>     tokenizer=tokenizer,
>     max_seq_length=max_tokens,
>     train_dataset=dataset,
>     eval_dataset=None,
>     peft_config=None,
>     args=training_args,
>     dataset_text_field="text",
> )
> ```

ValueError: Unable to create tensor, you should probably activate truncation and/or padding with 'padding=True' 'truncation=True' to have batched tensors with the same length. Perhaps your features (text in this case) have excessive nesting (inputs type list where type int is expected).

**Comment by mobicham** [comment]
Same issue I reported to the Hugging Face team: https://github.com/huggingface/trl/issues/1351 
It seems that some versions of trl have this issue.

@ Sneakr you were able to use SFTTrainer with HQQ/LoRA? If so, which versions of transformers and trl did you use?

**Comment by Minami-su** [comment]
https://github.com/fahadh4ilyas/peft/tree/hqq-lora
This peft branch version is available. Thank you very much.@fahadh4ilyas
![image](https://github.com/mobiusml/hqq/assets/76865636/75d9a22d-9ed3-4b9d-a219-cbb739435c86)

**Comment by mobicham** [comment]
Awesome, thanks @fahadh4ilyas !
Thanks @Sneakr for sharing the peft/transformers versions!

**Comment by YangYang-DLUT** [comment]
Sorry to bother, I met the same problem. I use  trl Version: 0.8.1 and transformers Version: 4.39.3 and the original `train_hqq_lora_example.py`,the error still occurs:
``ValueError: Unable to create tensor, you should probably activate truncation and/or padding with 'padding=True' 'truncation=True' to have batched tensors with the same length. Perhaps your features (text in this case) have excessive nesting (inputs type list where type int is expected).``

Then I pull the `hqq-lora`branch of peft and install it , set like this :
```
peft_config = LoraConfig (
    target_modules=["q_proj","v_proj"],
    task_type="CAUSAL_LM",
    r=32,
    lora_alpha=64,
    lora_dropout=0.05,
    bias="none"
)

model = get_peft_model(model,peft_config)
```
Still get the same error 😢 
```
oading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.37s/it]
/mnt/dolphinfs/ssd_pool/docker/user/hadoop-automl/yangyang260/conda_env/hqq/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:492: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
  warnings.warn(
/mnt/dolphinfs/ssd_pool/docker/user/hadoop-automl/yangyang260/conda_env/hqq/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:497: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
  warnings.warn(
/mnt/dolphinfs/ssd_pool/docker/user/hadoop-automl/yangyang260/conda_env/hqq/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:492: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/mnt/dolphinfs/ssd_pool/docker/user/hadoop-automl/yangyang260/conda_env/hqq/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:497: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 32/32 [00:00<00:00, 134.52it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 32/32 [00:47<00:00,  1.49s/it]
Error.  nthreads cannot be larger than environment variable "NUMEXPR_MAX_THREADS" (64)Repo card metadata block was not found. Setting CardData to empty.
Repo card metadata block was not found. Setting CardData to empty.
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5000/5000 [00:00<00:00, 36811.00it/s]
/mnt/dolphinfs/ssd_pool/docker/user/hadoop-automl/yangyang260/conda_env/hqq/lib/python3.10/site-packages/trl/trainer/sft_trainer.py:471: UserWarning: You passed `remove_unused_columns=False` on a non-packed dataset. This might create some issues with the default collator and yield to errors. If you want to inspect dataset other columns (in this case ['text']), you can subclass `DataCollatorForLanguageModeling` in case you used the default collator and create your own data collator in order to inspect the unused dataset columns.
  warnings.warn(
Map: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5000/5000 [00:01<00:00, 3646.17 examples/s]
/mnt/dolphinfs/ssd_pool/docker/user/hadoop-automl/yangyang260/conda_env/hqq/lib/python3.10/site-packages/accelerate/accelerator.py:432: FutureWarning: Passing the following arguments to `Accelerator` is deprecated and will be removed in version 1.0 of Accelerate: dict_keys(['dispatch_batches', 'split_batches', 'even_batches', 'use_seedable_sampler']). Please pass an `accelerate.DataLoaderConfiguration` instead: 
dataloader_config = DataLoaderConfiguration(dispatch_batches=None, split_batches=False, even_batches=True, use_seedable_sampler=True)
  warnings.warn(
Detected kernel version 4.18.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
  0%|                                                                                                                                       | 0/312 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/mnt/dolphinfs/ssd_pool/docker/user/hadoop-automl/yangyang260/conda_env/hqq/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 759, in convert_to_tensors
    tensor = as_tensor(value)
  File "/mnt/dolphinfs/ssd_pool/docker/user/hadoop-automl/yangyang260/conda_env/hqq/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 721, in as_tensor
    return torch.tensor(value)
ValueError: too many dimensions 'str'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/dolphinfs/ssd_pool/docker/user/hadoop-automl/yangyang260/proj/hqq/examples/lora/train_hqq_lora_example.py", line 159, in <module>
    trainer.train()
  File "/mnt/dolphinfs/ssd_pool/docker/user/hadoop-automl/yangyang260/conda_env/hqq/lib/python3.10/site-packages/trl/trainer/sft_trainer.py", line 360, in train
    output = super().train(*args, **kwargs)
  File "/mnt/dolphinfs/ssd_pool/docker/user/hadoop-automl/yangyang260/conda_env/hqq/lib/python3.10/site-packages/transformers/trainer.py", line 1780, in train
    return inner_training_loop(
  File "/mnt/dolphinfs/ssd_pool/docker/user/hadoop-automl/yangyang260/conda_env/hqq/lib/python3.10/site-packages/transformers/trainer.py", line 2085, in _inner_training_loop
    for step, inputs in enumerate(epoch_iterator):
  File "/mnt/dolphinfs/ssd_pool/docker/user/hadoop-automl/yangyang260/conda_env/hqq/lib/python3.10/site-packages/accelerate/data_loader.py", line 452, in __iter__
    current_batch = next(dataloader_iter)
  File "/mnt/dolphinfs/ssd_pool/docker/user/hadoop-automl/yangyang260/conda_env/hqq/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/mnt/dolphinfs/ssd_pool/docker/user/hadoop-automl/yangyang260/conda_env/hqq/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 677, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/mnt/dolphinfs/ssd_pool/docker/user/hadoop-automl/yangyang260/conda_env/hqq/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "/mnt/dolphinfs/ssd_pool/docker/user/hadoop-automl/yangyang260/conda_env/hqq/lib/python3.10/site-packages/transformers/data/data_collator.py", line 45, in __call__
    return self.torch_call(features)
  File "/mnt/dolphinfs/ssd_pool/docker/user/hadoop-automl/yangyang260/conda_env/hqq/lib/python3.10/site-packages/transformers/data/data_collator.py", line 761, in torch_call
    batch = pad_without_fast_tokenizer_warning(
  File "/mnt/dolphinfs/ssd_pool/docker/user/hadoop-automl/yangyang260/conda_env/hqq/lib/python3.10/site-packages/transformers/data/data_collator.py", line 66, in pad_without_fast_tokenizer_warning
    padded = tokenizer.pad(*pad_args, **pad_kwargs)
  File "/mnt/dolphinfs/ssd_pool/docker/user/hadoop-automl/yangyang260/conda_env/hqq/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 3369, in pad
    return BatchEncoding(batch_outputs, tensor_type=return_tensors)
  File "/mnt/dolphinfs/ssd_pool/docker/user/hadoop-automl/yangyang260/conda_env/hqq/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 224, in __init__
    self.convert_to_tensors(tensor_type=tensor_type, prepend_batch_axis=prepend_batch_axis)
  File "/mnt/dolphinfs/ssd_pool/docker/user/hadoop-automl/yangyang260/conda_env/hqq/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 775, in convert_to_tensors
    raise ValueError(
ValueError: Unable to create tensor, you should probably activate truncation and/or padding with 'padding=True' 'truncation=True' to have batched tensors with the same length. Perhaps your features (`text` in this case) have excessive nesting (inputs type `list` where type `int` is expected).
  0%|          | 0/312 [00:00<?, ?it/s] 
```
the training setting is 
```
#####################################################################################
#Train
from trl import SFTTrainer

grad_acc   = 2
logging_st = 1
max_steps  = -1
lr         = 1e-4 
batch_size = 1
n_epochs   = 1

training_args = transformers.TrainingArguments(
    output_dir='.',	
    per_device_train_batch_size=batch_size,
    #per_device_eval_batch_size=batch_size,
    gradient_accumulation_steps=grad_acc,
    learning_rate=lr,
    logging_steps=logging_st,
    num_train_epochs=n_epochs,
    max_steps=max_steps,
    #evaluation_strategy = "epoch",
    remove_unused_columns=False,
    #logging_strategy="epoch",
    fp16=train_dtype==torch.float32,
    max_grad_norm=1.0,
    save_steps=10000000,
    lr_scheduler_type= "linear", 
)

#Wrap model to avoid accelerate issues 
class WrappedModel(torch.nn.Module):
	def __init__(self, model):
		super().__init__()
		self.model = model

	def forward(self, *args, **kwargs):
		return self.model.forward(*args, **kwargs)

	def train(self):
		self.model.train()

	def eval(self):
		self.model.eval()

	def parameters(self):
		return self.model.parameters()

trainer = SFTTrainer(
    model=WrappedModel(model),
    tokenizer=tokenizer,
    max_seq_length=max_tokens,
    train_dataset=dataset,
    eval_dataset=None,
    peft_config=None,
    args=training_args,
    dataset_text_field="text",
    # packing=True,
)

model.is_parallelizable       = False
trainer.is_model_parallel     = False
trainer.place_model_on_device = False

model.train()
trainer.train()
```
Could anyone help me out? Thanks so much 🥹

**Comment by mobicham** [comment]
@Minami-su can you please share a code snippet with https://github.com/fahadh4ilyas/peft/tree/hqq-lora so that @YangYang-DLUT can use it ? Thanks a lot!

**Comment by Sneakr** [comment]
@YangYang-DLUT I think this is because of your dataset format and you are not preparing it correctly, I'm not an expert but I have made my own dataset format that I'm training with and experimenting with.

For different datasets you have different methods https://huggingface.co/docs/datasets/en/tutorial

Here's my code:

```
dataset_files = [
	"dataset/math_instruction.jsonl",
]

# Load the combined dataset
dataset = load_dataset("json", data_files=dataset_files, split="train")

```
```
trainer = SFTTrainer(
	model=WrappedModel(model),
	tokenizer=tokenizer,
	max_seq_length=max_tokens,
	train_dataset=dataset,
	eval_dataset=None,
	peft_config=None,
	args=training_args,
	packing=True,
	neftune_noise_alpha=5,
)
```
Notice I need packing=True for my dataset format to work and not use dataset_text_field="text". 

If you use dataset_text_field="text", your dataset must be different format than mine and make some extra steps.

My dataset is custom format and might not fit your use case as I'm experimenting only:

`{"prompt": "How can I treat calluses on my feet?", "completion": "Calluses are a buildup of hard skin on your feet that make walking less comfortable.  It usually forms as a response to over-use.\n"}`

they are in .jsonl format I load locally from a folder.

**Comment by Minami-su** [comment]
> @Minami-su can you please share a code snippet with https://github.com/fahadh4ilyas/peft/tree/hqq-lora so that @YangYang-DLUT can use it ? Thanks a lot!

Hey, here's my code.https://github.com/Minami-su/character_AI_open/blob/main/ft-bit--hqq-lora-sft.py

**Comment by Minami-su** [comment]
> Thanks @Minami-su !
> 
> By the way, HQQ-quantized models don't support `.cuda()` or `.half() `: https://github.com/Minami-su/character_AI_open/blob/main/ft-bit--hqq-lora-sft.py#L270 If you are trying to train with bfloat16, that code would not work properly, instead use the following:
> 
> ```python
> device = 'cuda' # your cude device
> compute_dtype = torch.float16 # dtype: float16, bfloat16
> 
> model = AutoTokenizer.from_pretrained(model_id, device=device, compute_dtype=compute_dtype)
> ...
> model = AutoHQQHFModel.from_quantized(qmodel_id, device=device, compute_dtype=compute_dtype)
> ```

Thank you very much!
