### ISSUE TITLE
Why does the 2bit 34b model take up 19GB of GPU memory

### ISSUE THREAD

**Issue by Minami-su** [mobiusml/hqq#44]
quant_config = BaseQuantizeConfig(nbits=2, group_size=16,offload_meta=False)
![image](https://github.com/mobiusml/hqq/assets/76865636/52a5cb77-84b3-40e2-8889-3d153a4fc1da)

Quip# 's 2bit 34b model is around 12GB of memory

**Comment by Minami-su** [comment]
emmmm......
![image](https://github.com/mobiusml/hqq/assets/76865636/960c8f95-5439-4c33-9f88-13d7ad67c869)

**Comment by mobicham** [comment]
Because you need to use `offload_meta=True`

**Comment by Minami-su** [comment]
> Because you need to use `offload_meta=True`

19GB is inference mode.

**Comment by Minami-su** [comment]
And I want to know the quantize config of HQQ_g16_s*

**Comment by Minami-su** [comment]
> Because you need to use `offload_meta=True`

I'm sorry I was stupid.

**Comment by mobicham** [comment]
> And I want to know the quantize config of HQQ_g16_s*
https://github.com/mobiusml/hqq/blob/master/examples/llama2_benchmark/quant_llama2_hqq_demo.py#L25
