### ISSUE TITLE
Difference between blog post and implementation

### ISSUE THREAD

**Issue by dacorvo** [mobiusml/hqq#45]
Looking at the HQQ implementation, I found a difference with what is described in the article that I don't understand: the optimization seems to apply formulas for Lp, but actually iterates by checking L1 only:

https://github.com/mobiusml/hqq/blob/3bb6bbb7088e02fe41c9cffae0b5b733473f1066/hqq/core/optimize.py#L212

**Comment by mobicham** [comment]
Hi, that's the just the early stopping criterion, that value is not used to update the parameters. The actual lp-norm is used in the Lp shrinking operator: https://github.com/mobiusml/hqq/blob/3bb6bbb7088e02fe41c9cffae0b5b733473f1066/hqq/core/optimize.py#L208
You can also use the lp-norm as a stopping criterion like here: https://github.com/mobiusml/hqq/blob/3bb6bbb7088e02fe41c9cffae0b5b733473f1066/hqq/core/optimize.py#L152 but that is a bit unstable at low lp-values, meaning it leads to the optimizer stopping earlier. 

This has been addressed before here: https://github.com/mobiusml/hqq/issues/10#issuecomment-1877442330 

Hope that answers your question!
