### ISSUE TITLE
Request for amd support

### ISSUE THREAD

**Issue by Wintoplay** [mobiusml/hqq#49]
Please consider adding support for consumer grade amd gpu like 7900xtx

**Comment by mobicham** [comment]
@Wintoplay It should work with the pytorch compile backend. Have you tried it?

**Comment by Wintoplay** [comment]
Out of memory for cpu part. (32 gb)
Use only 13 gb for gpu vram.

**Comment by Wintoplay** [comment]
Oh, I see.that's why cpu goes OOM. It is mixtral 8x7 4bit for router and 2 bit for experts.

**Comment by mobicham** [comment]
Use this pre-quantized model instead: https://huggingface.co/mobiuslabsgmbh/Mixtral-8x7B-Instruct-v0.1-hf-attn-4bit-moe-2bitgs8-metaoffload-HQQ
