### ISSUE TITLE
SafetensorError: Error while deserializing header: HeaderTooLarge

### ISSUE THREAD

**Issue by drewskidang** [mobiusml/hqq#5]
using fintune mixtral but getting 

File /opt/conda/lib/python3.10/site-packages/transformers/modeling_utils.py:4091, in PreTrainedModel._load_pretrained_model(cls, model, state_dict, loaded_keys, resolved_archive_file, pretrained_model_name_or_path, ignore_mismatched_sizes, sharded_metadata, _fast_init, low_cpu_mem_usage, device_map, offload_folder, offload_state_dict, dtype, is_quantized, keep_in_fp32_modules)
   4089 if shard_file in disk_only_shard_files:
   4090     continue
-> 4091 state_dict = load_state_dict(shard_file)
   4093 # Mistmatched keys contains tuples key/shape1/shape2 of weights in the checkpoint that have a shape not
   4094 # matching the weights in the model.
   4095 mismatched_keys += _find_mismatched_keys(
   4096     state_dict,
   4097     model_state_dict,
   (...)
   4101     ignore_mismatched_sizes,
   4102 )

File /opt/conda/lib/python3.10/site-packages/transformers/modeling_utils.py:503, in load_state_dict(checkpoint_file)
    498 """
    499 Reads a PyTorch checkpoint file, returning properly formatted errors if they arise.
    500 """
    501 if checkpoint_file.endswith(".safetensors") and is_safetensors_available():
    502     # Check format of the archive
--> 503     with safe_open(checkpoint_file, framework="pt") as f:
    504         metadata = f.metadata()
    505     if metadata.get("format") not in ["pt", "tf", "flax"]:

**Comment by mobicham** [comment]
Can you please share the code snippet that produced this error? HQQ doesn't call `_load_pretrained_model` from transformers
