### ISSUE TITLE
 torch.compile() for quantized model

### ISSUE THREAD

**Issue by DHKim0428** [mobiusml/hqq#64]
Hi,

I'm encountering errors when trying to compile a custom model using torch.compile() after replacing nn.Linear() with HQQLinear. Below is a minimal code snippet that reproduces the issue, along with the error messages.

Environment:

PyTorch version: 2.3.0

Code to Reproduce Issue:

```python
import torch
import torch.nn as nn
from hqq.core import HQQLinear, BaseQuantizeConfig

class TestModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(320, 640)
        self.fc2 = nn.Linear(640, 320)

    def forward(self, x):
        return self.fc2(self.fc1(x))

model = TestModel().to('cuda')
rand_inps = torch.randn(1, 320).to('cuda')

quant_config = BaseQuantizeConfig(
    nbits=4, group_size=32, quant_zero=False,
    quant_scale=False, offload_meta=False, axis=0
)

hqq_layer = HQQLinear(
    model.fc1, quant_config=quant_config, compute_dtype=torch.float32,
    device='cuda', initialize=True, del_orig=True
)
setattr(model, "fc1", hqq_layer)

model = torch.compile(model, mode='max-autotune', fullgraph=True)
rand_out = model(rand_inps)
```

Error Messages:

```
Unsupported: NYI - autograd.Function with custom setup_context method
from user code:
   File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
```
In some model, an ArgsMismatchError occurs:
```
ArgsMismatchError: too many positional arguments.
  func = 'forward' /opt/conda/lib/python3.10/site-packages/hqq/core/quantize.py:254, args = [<class 'torch.autograd.function.Function'>, <class 'torch.Tensor'>, <class 'method'>, <class 'torch.nn.parameter.Parameter'>], kwargs = {}
```

However, when I run the `examples/hf/mixtral_13GB_example.py` provided in this repo, I checked that torch.compile() is working without issues. I'm not sure why my approach isn't working.

Could you advise on the correct implementation steps for compiling a quantized model? 

Thank you in advance for your assistance.

**Comment by mobicham** [comment]
Hi @DHKim0428 
It should work with fullgraph, but only for the forward pass. It breaks because by default, `HQQLinear` is training-ready but the backward pass as it is implemented right now is not compatible with fullgraph (but would work fine with `fullgraph=False`)
Try this:

1- Apply inference patching:
```Python
from hqq.utils.patching import patch_hqq_inference
hqq_layer = patch_hqq_inference(hqq_layer)
```
2- Set backend to `PYTORCH`:
```Python
from hqq.core.quantize import HQQLinear, HQQBackend
HQQLinear.set_backend(HQQBackend.PYTORCH) 
```

3-Compile the forward pass not the model, and use `torch.no_grad()`:
```Python
model.forward = torch.compile(model.forward, mode='max-autotune', fullgraph=True)
with torch.no_grad():
   rand_out = model(rand_inps)
```

**Comment by DHKim0428** [comment]
Oh, that `patch_hqq_inference()` and `patch_add_weight_param()` make it works! Thank you for your kind help ;)

**Comment by mobicham** [comment]
FYI `patch_add_weight_param` is mainly useful for Hugging Face models with a static cache. 
Full example with `fullgraph` compile : https://github.com/mobiusml/hqq/blob/master/examples/backends/torchao_int4_demo.py
