### ISSUE TITLE
Issues with HQQLinear compatability when quantized from bf16. 

### ISSUE THREAD

**Issue by michaelfeil** [mobiusml/hqq#7]
I am trying to integrate hqq as drop-in replacement for Bitsandbytes-4bit in Huggingface's TGI.

E.g. my approach is to quantize on the fly, similar to this line in bitsandbytes.
https://github.com/huggingface/text-generation-inference/blob/630800eed37b15c4b0c9eb8e6ab47212026720f7/server/text_generation_server/utils/layers.py#L317

```python
elif quantize.startswith("hqq"):
    HQQLinear.set_backend(HQQBackend.PYTORCH)
    layer = nn.Linear(weight.shape[1], weight.shape[0], bias=bias is not None, dtype=weight.dtype)
        with torch.no_grad():
            layer.weight.data = weight
            if bias is not None:
                layer.bias.data = bias
    linear = HQQLinear(layer, BaseQuantizeConfig(nbits=4, group_size=64, quant_zero=True, quant_scale=False), del_orig=True)
```

Using a float16 model, this works, however with bfloat16, it fails.
Example model: `TinyLlama/TinyLlama-1.1B-Chat-v0.3`

#### Produces Error in Backend.PYTORCH

```
  File "../.venv/lib/python3.10/site-packages/hqq/core/quantize.py", line 217, in forward_pytorch
    out   = torch.matmul(x, W_est.t())
RuntimeError: expected mat1 and mat2 to have the same dtype, but got: c10::BFloat16 != c10::Half
```

#### Produces Error in Backend.PYTORCH_COMPILE
```
tgi/utils/layers.py", line 531, in forward
    rotary_emb.apply_rotary(x1, x2, cos, sin, x1, x2, False)
RuntimeError: Expected x1.dtype() == cos.dtype()
```
x1 is float32, cos is bfloat16 / same as unquantized layer.

**Comment by mobicham** [comment]
Regarding the first error, that's expected because we have to cast the weights after bit-unpacking and by default it's using half.  The code snippet below should temporarily solve your problem. In the future, the user will be able to specify the dtype:
```python
## Add this in the beginning before quantizing anything 
import torch
from hqq.core.quantize import Quantizer

def dequantize_bfp16(cls, W_q, meta):
	W_q_p = Quantizer.unpack[meta['packing']](W_q).to(torch.bfloat16)
	if((meta['group_size'] is not None) and (meta['nbits']==3)):
		W_q_p = W_q_p[:meta['group_size']] if (meta['axis']==0) else W_q_p[:,:meta['group_size']]
	W_r = ((W_q_p - meta['zero'])*meta['scale']).reshape(meta['shape']) 
	del W_q_p
	return W_r

def to_inplace_bfp16(cls, W_q, meta, device):
	W_q = W_q.to(device).contiguous() 
	for key in meta:
		if(type(meta[key])==torch.Tensor):
			meta[key] = (meta[key].to(torch.bfloat16) if meta[key].dtype==torch.float32 else meta[key]).to(device).contiguous() 
	return W_q, meta

Quantizer.dequantize = dequantize_bfp16
Quantizer.to_inplace = to_inplace_bfp16

## then replace linear = HQQLinear(layer,...);
## Re-cast bias after conversion 
linear.bias = linear.bias.to(torch.bfloat16) if (linear.bias is not None) else None
```

Regarding the second error, I am not sure, that's related to the rotary embedding layer which is not quantized. The compile backend only compiles the forward pass of HQQLinear. Maybe this will be resolved with proper bfloat16 casting with the snippet above. 
Let me know if that works!

**Comment by mobicham** [comment]
You can now specify ```compute_dtype``` when quantizing models, setting it to ```torch.bfloat16``` should fix this issue! Feel free to re-open if it doesn't work.
