### ISSUE TITLE
Is HQQLinearLoRAWithFakeQuant differentiable?

### ISSUE THREAD

**Issue by lippman1125** [mobiusml/hqq#84]
Is HQQLinearLoRAWithFakeQuant differentiable? Since torch.round is not differentiable and is called by HQQLinearLoRAWithFakeQuant, do we need to use round_ste instead of torch.round?

**Comment by mobicham** [comment]
Yeah, that was just an experimental placeholder that I forgot to remove actually, should not be used. 
I practice, I noticed that ste is not working well with 4-bit/3-bit for some reason. Better to just freeze the quantized weights and train LoRA weights instead to not deal without gradient issues and large vram requirements (HQQ+).
