### ISSUE TITLE
hqq+ lora ValueError || ValueError: Unable to create tensor, you should probably activate truncation and/or padding with 'padding=True' 'truncation=True'

### ISSUE THREAD

**Issue by tellyoung** [mobiusml/hqq#85]
ValueError: Unable to create tensor, you should probably activate truncation and/or padding with 'padding=True' 'truncation=True' to have batched tensors with the same length. Perhaps your features (`text` in this case) have excessive nesting (inputs type `list` where type `int` is expected).

**Comment by mobicham** [comment]
Can you please explain a bit and provide a code snippet to reproduce the error?

**Comment by SAIVENKATARAJU** [comment]
This issue happening from here: https://github.com/mobiusml/hqq/blob/master/examples/lora/train_hqq_lora_example.py

**Comment by mobicham** [comment]
Hi, that's an old issue. HQQ works directly in Peft for a while now: https://huggingface.co/docs/peft/developer_guides/quantization#hqq-quantization
